// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xthikjwrmavqenukhbpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0aGlrandybWF2cWVudWtoYnB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwOTc0NjcsImV4cCI6MjA2OTY3MzQ2N30.kICjBydrsi69Plsen5DevgW3oS0jKRjEFj8OHfQwYUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});